import type { AssignmentCapability } from "@/lib/assignment-capabilities";
import type {
  AssignmentProfileInput,
  SubjectDomain,
} from "@/lib/assignment-profile";

export const GOLDEN_ASSIGNMENT_CATEGORIES = [
  "physical_education",
  "health",
  "accounting",
  "economics",
  "geography",
  "engineering",
  "trade_cte",
  "music",
  "theatre",
  "dance",
  "cad",
  "advanced_technical_lab",
  "mathematics",
  "writing",
  "history_dbq",
  "science_lab",
  "reading",
  "world_language",
  "coding",
  "visual_arts_project",
  "interdisciplinary_project",
] as const;

export type GoldenAssignmentCategory =
  (typeof GOLDEN_ASSIGNMENT_CATEGORIES)[number];

export type GoldenAssignmentSourceState = "complete" | "partial" | "none";
export type GoldenAssignmentSourceFormat =
  | "inline"
  | "pdf"
  | "worksheet"
  | "pdf_worksheet"
  | "none";
export type GoldenAssignmentAiPolicy = "green" | "yellow" | "red";

export type GoldenAssignmentFixture = {
  id: string;
  category: GoldenAssignmentCategory;
  input: AssignmentProfileInput;
  expectedSubject: SubjectDomain;
  intendedCapabilities: readonly AssignmentCapability[];
  sourceState: GoldenAssignmentSourceState;
  sourceFormat: GoldenAssignmentSourceFormat;
  aiPolicy: GoldenAssignmentAiPolicy;
  mixedCapability: boolean;
};

export const GOLDEN_ASSIGNMENTS = [
  {
    id: "pe-volleyball-skill-log",
    category: "physical_education",
    input: {
      kind: "other",
      className: "Physical Education",
      title: "Volleyball skill practice and movement log",
      description: "Record practice evidence and reflect on serving technique.",
    },
    expectedSubject: "physical_education",
    intendedCapabilities: ["performance_log", "video_review", "rich_text"],
    sourceState: "none",
    sourceFormat: "none",
    aiPolicy: "red",
    mixedCapability: true,
  },
  {
    id: "health-nutrition-source-review",
    category: "health",
    input: {
      kind: "reading",
      className: "Health Education",
      title: "Nutrition literacy source review and wellness reflection",
      sourceText: "Compare each claim with the cited public-health evidence.",
    },
    expectedSubject: "health",
    intendedCapabilities: ["rich_text", "performance_log", "audio_review"],
    sourceState: "complete",
    sourceFormat: "inline",
    aiPolicy: "yellow",
    mixedCapability: true,
  },
  {
    id: "accounting-journal-worksheet",
    category: "accounting",
    input: {
      kind: "other",
      className: "Accounting I",
      title: "Journal entries and trial balance worksheet",
      description: "Post the transactions, balance the accounts, and explain the result.",
      sourceText: "Transaction 1: Owner invested $8,000 cash in the business.",
    },
    expectedSubject: "accounting",
    intendedCapabilities: [
      "accounting_ledger",
      "spreadsheet",
      "equation_editor",
      "rich_text",
    ],
    sourceState: "complete",
    sourceFormat: "pdf_worksheet",
    aiPolicy: "green",
    mixedCapability: true,
  },
  {
    id: "accounting-partial-income-statement",
    category: "accounting",
    input: {
      kind: "other",
      className: "Business Finance",
      title: "Prepare an accounting income statement",
      description: "Use the uploaded worksheet and identify any missing figures.",
      sourceText: "Extracted page 1 of 2: Revenue 12,400; supplies expense 1,175.",
    },
    expectedSubject: "accounting",
    intendedCapabilities: [
      "accounting_ledger",
      "spreadsheet",
      "equation_editor",
      "rich_text",
    ],
    sourceState: "partial",
    sourceFormat: "pdf_worksheet",
    aiPolicy: "red",
    mixedCapability: true,
  },
  {
    id: "economics-supply-demand-model",
    category: "economics",
    input: {
      kind: "presentation",
      className: "Economics",
      title: "Supply and demand market equilibrium model",
      description: "Graph both curves, calculate equilibrium, and support the analysis with data.",
    },
    expectedSubject: "economics",
    intendedCapabilities: ["graphing", "spreadsheet", "rich_text"],
    sourceState: "none",
    sourceFormat: "none",
    aiPolicy: "green",
    mixedCapability: true,
  },
  {
    id: "economics-fiscal-policy-pdf",
    category: "economics",
    input: {
      kind: "reading",
      className: "AP Economics",
      title: "Fiscal policy source analysis",
      sourceText: "The report compares public spending, tax revenue, and GDP over ten years.",
    },
    expectedSubject: "economics",
    intendedCapabilities: ["graphing", "spreadsheet", "rich_text"],
    sourceState: "complete",
    sourceFormat: "pdf",
    aiPolicy: "yellow",
    mixedCapability: true,
  },
  {
    id: "geography-choropleth-project",
    category: "geography",
    input: {
      kind: "presentation",
      className: "Human Geography",
      title: "Population-density choropleth and spatial pattern analysis",
      description: "Create a sourced map, chart the data, and explain regional patterns.",
    },
    expectedSubject: "geography",
    intendedCapabilities: [
      "map_workspace",
      "drawing_canvas",
      "spreadsheet",
      "graphing",
      "rich_text",
    ],
    sourceState: "none",
    sourceFormat: "none",
    aiPolicy: "yellow",
    mixedCapability: true,
  },
  {
    id: "engineering-bridge-prototype",
    category: "engineering",
    input: {
      kind: "presentation",
      className: "Principles of Engineering",
      title: "Bridge prototype with design constraints and bill of materials",
      description: "Compare alternatives, calculate load, build a model, and document testing.",
    },
    expectedSubject: "engineering",
    intendedCapabilities: [
      "design_notebook",
      "equation_editor",
      "graphing",
      "spreadsheet",
      "drawing_canvas",
      "cad_workspace",
      "rich_text",
    ],
    sourceState: "complete",
    sourceFormat: "inline",
    aiPolicy: "green",
    mixedCapability: true,
  },
  {
    id: "trade-cte-welding-procedure",
    category: "trade_cte",
    input: {
      kind: "other",
      className: "Welding CTE",
      title: "Welding shop procedure and joint-quality evidence",
      description: "Follow the approved procedure, record measurements, and submit reflection evidence.",
      sourceText: "Partial extraction: approved setup checks and required PPE are on page 2.",
    },
    expectedSubject: "trade_cte",
    intendedCapabilities: [
      "procedure_checklist",
      "design_notebook",
      "data_lab",
      "drawing_canvas",
      "video_review",
      "rich_text",
    ],
    sourceState: "partial",
    sourceFormat: "pdf",
    aiPolicy: "red",
    mixedCapability: true,
  },
  {
    id: "music-composition-score",
    category: "music",
    input: {
      kind: "presentation",
      className: "Music Theory",
      title: "MusicXML composition and performance reflection",
      description: "Notate an original phrase, review playback, record a performance, and reflect.",
    },
    expectedSubject: "music",
    intendedCapabilities: [
      "music_notation",
      "audio_review",
      "performance_log",
      "rich_text",
    ],
    sourceState: "none",
    sourceFormat: "none",
    aiPolicy: "green",
    mixedCapability: true,
  },
  {
    id: "theatre-monologue-packet",
    category: "theatre",
    input: {
      kind: "reading",
      className: "Theatre Arts",
      title: "Monologue scene study and rehearsal portfolio",
      sourceText: "Selected monologue, performance rubric, and blocking notes.",
    },
    expectedSubject: "theatre",
    intendedCapabilities: [
      "rich_text",
      "design_notebook",
      "video_review",
      "audio_review",
      "performance_log",
    ],
    sourceState: "complete",
    sourceFormat: "pdf",
    aiPolicy: "yellow",
    mixedCapability: true,
  },
  {
    id: "dance-choreography-portfolio",
    category: "dance",
    input: {
      kind: "presentation",
      className: "Modern Dance",
      title: "Choreography movement phrase rehearsal portfolio",
      description: "Plan, record, revise, and reflect on the movement phrase.",
    },
    expectedSubject: "dance",
    intendedCapabilities: [
      "design_notebook",
      "video_review",
      "performance_log",
      "rich_text",
    ],
    sourceState: "none",
    sourceFormat: "none",
    aiPolicy: "red",
    mixedCapability: true,
  },
  {
    id: "cad-bracket-model",
    category: "cad",
    input: {
      kind: "presentation",
      className: "CAD Foundations",
      title: "CAD dimensioned sketch and STL bracket model",
      description: "Create the constrained sketch, inspect the model, and document revisions.",
      sourceText: "Bracket requirements: 80 mm by 40 mm with two 8 mm holes.",
    },
    expectedSubject: "cad",
    intendedCapabilities: [
      "cad_workspace",
      "drawing_canvas",
      "design_notebook",
      "rich_text",
    ],
    sourceState: "complete",
    sourceFormat: "pdf",
    aiPolicy: "green",
    mixedCapability: true,
  },
  {
    id: "advanced-chemistry-titration",
    category: "advanced_technical_lab",
    input: {
      kind: "lab",
      className: "AP Chemistry",
      title: "Advanced technical lab: acid-base titration",
      description: "Use the approved procedure, record uncertainty, graph results, and explain error.",
      sourceText: "Partial extraction: teacher-approved procedure version 3; endpoint table follows.",
    },
    expectedSubject: "advanced_technical_labs",
    intendedCapabilities: [
      "procedure_checklist",
      "data_lab",
      "equation_editor",
      "graphing",
      "spreadsheet",
      "design_notebook",
      "rich_text",
    ],
    sourceState: "partial",
    sourceFormat: "pdf",
    aiPolicy: "red",
    mixedCapability: true,
  },
  {
    id: "math-quadratic-worksheet",
    category: "mathematics",
    input: {
      kind: "problem_set",
      className: "Algebra II",
      title: "Quadratic equations worksheet",
      description: "Solve each equation, graph the function, and explain one solution.",
      sourceText: "1. Solve x^2 - 5x + 6 = 0. 2. Graph y = x^2 - 4.",
    },
    expectedSubject: "mathematics",
    intendedCapabilities: ["equation_editor", "graphing", "rich_text"],
    sourceState: "complete",
    sourceFormat: "worksheet",
    aiPolicy: "yellow",
    mixedCapability: true,
  },
  {
    id: "math-statistics-partial-pdf",
    category: "mathematics",
    input: {
      kind: "problem_set",
      className: "Statistics",
      title: "Statistics sampling-distribution problem set",
      sourceText: "Extracted questions 1 through 4; the data table on page 2 is unavailable.",
    },
    expectedSubject: "mathematics",
    intendedCapabilities: ["equation_editor", "graphing", "rich_text"],
    sourceState: "partial",
    sourceFormat: "pdf_worksheet",
    aiPolicy: "green",
    mixedCapability: true,
  },
  {
    id: "writing-rhetorical-analysis",
    category: "writing",
    input: {
      kind: "essay",
      className: "English 11",
      title: "Rhetorical analysis essay",
      description: "Draft a claim and support it with quoted evidence from the speech.",
      sourceText: "The complete speech and teacher rubric are attached.",
    },
    expectedSubject: "english_language_arts",
    intendedCapabilities: ["rich_text"],
    sourceState: "complete",
    sourceFormat: "pdf",
    aiPolicy: "yellow",
    mixedCapability: false,
  },
  {
    id: "history-reconstruction-dbq",
    category: "history_dbq",
    input: {
      kind: "essay",
      className: "AP US History",
      title: "Reconstruction document-based question",
      description: "Analyze the primary sources and write a historical argument.",
      sourceText: "Documents A-C extracted; Documents D-F are still processing.",
    },
    expectedSubject: "social_studies",
    intendedCapabilities: ["rich_text"],
    sourceState: "partial",
    sourceFormat: "pdf",
    aiPolicy: "green",
    mixedCapability: false,
  },
  {
    id: "science-biology-enzyme-lab",
    category: "science_lab",
    input: {
      kind: "lab",
      className: "Biology",
      title: "Enzyme-rate laboratory investigation",
      description: "Follow the approved procedure, record data, graph rate, and explain findings.",
      sourceText: "Teacher procedure, data table template, and lab-report rubric.",
    },
    expectedSubject: "science",
    intendedCapabilities: [
      "procedure_checklist",
      "data_lab",
      "equation_editor",
      "graphing",
      "spreadsheet",
      "rich_text",
    ],
    sourceState: "complete",
    sourceFormat: "worksheet",
    aiPolicy: "yellow",
    mixedCapability: true,
  },
  {
    id: "reading-novel-response",
    category: "reading",
    input: {
      kind: "reading",
      className: "English Language Arts",
      title: "Novel chapter reading response",
      description: "Annotate the chapter and explain how the conflict develops.",
    },
    expectedSubject: "english_language_arts",
    intendedCapabilities: ["rich_text"],
    sourceState: "none",
    sourceFormat: "none",
    aiPolicy: "red",
    mixedCapability: false,
  },
  {
    id: "language-spanish-oral-response",
    category: "world_language",
    input: {
      kind: "other",
      className: "Spanish II",
      title: "Spanish oral response and written reflection",
      description: "Record a response to the prompt, then revise the written version.",
      sourceText: "Prompt: Describe a memorable community event in the past tense.",
    },
    expectedSubject: "world_language",
    intendedCapabilities: ["rich_text", "audio_review", "video_review"],
    sourceState: "complete",
    sourceFormat: "worksheet",
    aiPolicy: "green",
    mixedCapability: true,
  },
  {
    id: "coding-python-debugger",
    category: "coding",
    input: {
      kind: "other",
      className: "Computer Science",
      title: "Python algorithm debugging lab",
      description: "Run tests, repair the function, and explain the defect.",
      sourceText: "def median(values): return sorted(values)[len(values) // 2]",
    },
    expectedSubject: "computer_science",
    intendedCapabilities: ["code_runner", "rich_text"],
    sourceState: "complete",
    sourceFormat: "inline",
    aiPolicy: "yellow",
    mixedCapability: true,
  },
  {
    id: "visual-art-portrait-project",
    category: "visual_arts_project",
    input: {
      kind: "presentation",
      className: "Visual Art",
      title: "Mixed-media portrait and artist statement",
      description: "Create studies, document revisions, and write the final reflection.",
    },
    expectedSubject: "visual_arts",
    intendedCapabilities: ["drawing_canvas", "design_notebook", "rich_text"],
    sourceState: "none",
    sourceFormat: "none",
    aiPolicy: "green",
    mixedCapability: true,
  },
  {
    id: "interdisciplinary-community-capstone",
    category: "interdisciplinary_project",
    input: {
      kind: "presentation",
      className: "Senior Capstone",
      title: "Interdisciplinary community accessibility capstone",
      description: "Define the need, synthesize research from several classes, and present the final project.",
    },
    expectedSubject: "interdisciplinary",
    intendedCapabilities: ["design_notebook", "rich_text"],
    sourceState: "none",
    sourceFormat: "none",
    aiPolicy: "red",
    mixedCapability: true,
  },
  {
    id: "general-pdf-question-sheet",
    category: "interdisciplinary_project",
    input: {
      kind: "other",
      className: "Advisory",
      title: "Complete the uploaded question worksheet",
      description: "Answer all questions and attach the response.",
      sourceText: "Questions 1 through 10 were extracted from the uploaded PDF.",
    },
    expectedSubject: "general",
    intendedCapabilities: ["rich_text"],
    sourceState: "complete",
    sourceFormat: "pdf_worksheet",
    aiPolicy: "yellow",
    mixedCapability: false,
  },
] as const satisfies readonly GoldenAssignmentFixture[];
